import { NextResponse } from 'next/server';
import { createRouteClient } from '@/lib/supabase/server';

function markdownToHtml(md: string): string {
  return md
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^\- (.+)$/gm, '<li>$1</li>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/(<li>.*<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
    .replace(/\n\n/g, '<br><br>');
}

function extractSlides(content: string, title: string): string {
  const sections = content.split(/^## /m).filter(Boolean);
  let html = `<div class="slide"><div class="slide-title">${title}</div><div class="slide-subtitle">Generated by NEXUS HR AI · ${new Date().toLocaleDateString()}</div></div>`;
  sections.forEach(section => {
    const lines = section.split('\n');
    const heading = lines[0].replace(/^#+ /, '').trim();
    const body = lines.slice(1).join('\n');
    const bullets = body.match(/^- .+$/gm) || [];
    let slideContent = '';
    if (bullets.length > 0) {
      slideContent = `<ul>${bullets.slice(0, 6).map(b => `<li>${b.slice(2)}</li>`).join('')}</ul>`;
    } else {
      slideContent = `<p style="font-size:16px;color:#334155;line-height:1.6">${body.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').slice(0, 400)}</p>`;
    }
    html += `<div class="slide content-slide"><h2>${heading}</h2>${slideContent}</div>`;
  });
  return html;
}

export async function POST(req: Request) {
  try {
    const { report_id, format, section_key, company_id } = await req.json();
    const supabase = createRouteClient();

    if (report_id) {
      const { data: report } = await supabase.from('ai_reports').select('*').eq('id', report_id).single();
      if (!report) return NextResponse.json({ error: 'Report not found' }, { status: 404 });

      if (format === 'excel') {
        const snapshot = report.data_snapshot || {};
        const rows: any[] = [];
        if (snapshot.by_department) {
          rows.push(['Department Breakdown']); rows.push(['Department', 'Count']);
          snapshot.by_department.forEach((d: any) => rows.push([d.dept, d.count]));
          rows.push([]);
        }
        if (snapshot.by_nationality) {
          rows.push(['Nationality Breakdown']); rows.push(['Nationality', 'Count']);
          snapshot.by_nationality.forEach((n: any) => rows.push([n.nationality, n.count]));
          rows.push([]);
        }
        if (snapshot.critical_expiries?.length > 0) {
          rows.push(['Document Expiry Alerts']); rows.push(['Employee', 'Document', 'Days Left', 'Expiry Date']);
          snapshot.critical_expiries.forEach((e: any) => rows.push([e.name, e.doc, e.days, e.expiry]));
        }
        const csv = rows.map(r => r.join(',')).join('\n');
        return NextResponse.json({ content: csv, filename: `${(report.title || 'report').replace(/\s+/g, '-')}.csv`, mime: 'text/csv' });
      }

      if (format === 'word') {
        const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${report.title}</title>
<style>body{font-family:Calibri,Arial,sans-serif;margin:2cm;color:#1a1a2e}h1{color:#4F46E5;border-bottom:2px solid #4F46E5;padding-bottom:8px}h2{color:#334155;margin-top:20px}table{border-collapse:collapse;width:100%;margin:10px 0}th{background:#4F46E5;color:white;padding:8px}td{border:1px solid #E2E8F0;padding:8px}.meta{color:#64748B;font-size:12px;margin-bottom:20px}</style>
</head><body><h1>${report.title}</h1><p class="meta">Generated by NEXUS HR AI · ${new Date().toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})} · ${report.report_type} report</p>${markdownToHtml(report.content || '')}</body></html>`;
        return NextResponse.json({ content: html, filename: `${(report.title || 'report').replace(/\s+/g, '-')}.doc`, mime: 'application/msword' });
      }

      if (format === 'ppt') {
        const slides = extractSlides(report.content || '', report.title);
        const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${report.title}</title>
<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:Calibri,Arial,sans-serif;background:#1E1B4B}.slide{width:960px;min-height:540px;background:white;margin:20px auto;padding:60px;page-break-after:always}.slide:first-child{background:linear-gradient(135deg,#4F46E5,#7C3AED);color:white;display:flex;flex-direction:column;justify-content:center}.slide-title{font-size:36px;font-weight:bold;margin-bottom:12px}.slide-subtitle{font-size:18px;opacity:.8}.content-slide h2{color:#4F46E5;font-size:28px;border-bottom:3px solid #4F46E5;padding-bottom:10px;margin-bottom:20px}.content-slide ul{list-style:none}.content-slide ul li{padding:8px 0;padding-left:20px;position:relative;font-size:16px;color:#334155}.content-slide ul li::before{content:"●";color:#4F46E5;position:absolute;left:0}</style>
</head><body>${slides}</body></html>`;
        return NextResponse.json({ content: html, filename: `${(report.title || 'report').replace(/\s+/g, '-')}-presentation.html`, mime: 'text/html' });
      }
    }

    if (section_key && !report_id) {
      const { data: fields } = await supabase.from('section_field_configs')
        .select('*').eq('company_id', company_id).eq('section_key', section_key).order('display_order');

      let records: any[] = [];
      if (section_key === 'employee') {
        const { data } = await supabase.from('employees').select('*');
        records = data || [];
      } else if (section_key === 'candidate') {
        const { data } = await supabase.from('candidates').select('*');
        records = data || [];
      } else {
        const { data } = await supabase.from('custom_records').select('*').eq('section_id', section_key);
        records = (data || []).map(r => r.data);
      }

      if (!fields || fields.length === 0) {
        return NextResponse.json({ error: 'No field configuration found for this section' }, { status: 400 });
      }

      const headers = fields.map((f: any) => f.field_label);
      const rows = records.map(r => fields.map((f: any) => {
        const val = r[f.field_key];
        return val !== null && val !== undefined ? String(val) : '';
      }));
      const csv = [headers, ...rows].map(r => r.map(c => `"${c.replace(/"/g, '""')}"`).join(',')).join('\n');
      return NextResponse.json({ content: csv, filename: `${section_key}-export-${new Date().toISOString().split('T')[0]}.csv`, mime: 'text/csv' });
    }

    return NextResponse.json({ error: 'Invalid request' }, { status: 400 });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
